# Generated by Django 3.0 on 2020-01-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('picture', models.ImageField(upload_to='', verbose_name='Picture')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('text', models.TextField(verbose_name='Text')),
                ('url', models.URLField(null=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'ordering': ('name',),
            },
        ),
    ]
